### ISSUE TITLE
"Cannot find DatapathFix.exe"

### ISSUE THREAD

**Issue by 1984CJED** [Dyvinia/DatapathFixPlugin#14]
Whenever I press launch it comes up with an error saying "Cannot find DatapathFix.exe"

Technical details:
Frosty Mod Manager: 1.0.6.1
Game: BF2 (2017)
Datapath plugin: 1.5.1

**Comment by nani1023** [comment]
It is NFS HEAT, not BF2, but I was getting the same error.
I tried reinstalling 1.0.6.1, etc., but it never seemed to fix it, so I reinstalled the old version and was able to start it successfully and the mods were installed.
This may not be helpful since the game is different, but you can try it if you want.

**Comment by Dyvinia** [comment]
Incorrect installation
